### ISSUE TITLE
API for submitting events to EMS

### ISSUE THREAD

**Issue by ahatherly** [nhsconnect/Events-Management#1]
Now that we've agreed that publishers can POST events synchronously into the EMS we'll need to clarify that in the overview, and define the FHIR operation that should be used in the spec.

**Comment by bushra** [comment]
I'll arrange a discussion for us to look at this and issues 2 and 3 with a view to to updating the specification. If you do have any documentation that I can work with please do send it along.

**Comment by james-answer** [comment]
@ahatherly Do you feel like we need additional information above what is available on the updated specificaion within the develope branch (you can see it on the `netlify` published version of the branch https://ems-develop.netlify.com/publication_publish.html)?

For "define the FHIR operation" were you thinking to create an actual FHIR OperationDefinition or just make sure the requirements are clear in the specificaiton?

**Comment by james-answer** [comment]
Something went wrong with github and my commit has disappeared. I have made changes on the "develop" branch for the points in this github issue.

**Comment by james-answer** [comment]
Test

**Comment by james-answer** [comment]
Closing this as we have updated the spec in this area and there is other git issues open to address validation.
