### ISSUE TITLE
Page - Manage Subscription

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#14]
On the Manage Subscription page (https://developer.nhs.uk/apis/ems-beta/explore_manage_subscription.html) I assume the request will also require a JWT, certs and endpoints to be included the same as the Create Subscription page?

i.e. add the following

## Pre-requisites
Before a subscription can be created the following must be in place:

- The submitting system will require national assurance and be set up as a Spine Endpoint with an associated endpoint certificate (see here for details).
- All requests will include a JWT with information about the requesting system and user (see here for details).

**Comment by fletch1975** [comment]
Agree - these need to be added.

**Comment by fletch1975** [comment]
Resolved in latest version of specification.
