### ISSUE TITLE
Page - Subscriptions Overview

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#16]
The Subscriptions Overview page (https://developer.nhs.uk/apis/ems-beta/explore_subscriptions.html) could do with some additional information.

1. The page ecould do with an introduction as to what subscription is and who is going to be using this api.

**Comment by fletch1975** [comment]
Agree - I'll take an action to do this.

**Comment by james-answer** [comment]
Something else we could add to this page which would be useful for a subscriber to know would be: if two subscriptions were create by the same organization, for example a explicit subscription for a paitent and a rule based subscription for an event type, if an event came into NEMS which conformed to both subscriptions would the consumer get one or two event messages to their MESH mailbox.

**Comment by james-answer** [comment]
During a meeting yesterday, it was discussed that rule based subscription needs more work and is not going to be relased in bundle 1A and is currently not planned to be released within bundle 1B. Additional work needs to be done before it is estimate and planned for relase. This should be reflected in the spec so that there is no confusion by consumers as to what they can acutually subscribe to. We could either remove it from the spec people are going to build against for Bundle 1A or we can add a note to say that rule based subscriptions will not be available for bundle 1A.

**Comment by james-answer** [comment]
Made changes for for the points raised on this github issue. Changes on the "develop" branch.

**Comment by james-answer** [comment]
Something went wrong with github and my commit has disappeared. I have made changes on the "develop" branch for the points in this github issue.

**Comment by james-answer** [comment]
Somthing went wrong with my github comment, it has vanished. I have made the changes for this github issue on the "develop" branch.

**Comment by james-answer** [comment]
Reviewed and merged so closing issue.
