### ISSUE TITLE
Clarify responses to event publishers

### ISSUE THREAD

**Issue by ahatherly** [nhsconnect/Events-Management#2]
The spec includes an event response message, but we need to clarify the use of this. We need to be clear on what is returned in the response to the synchronous call into the EMS to post and event (OperationOutcome) vs what responses an event subscriber might expect to produce (errors, etc) to send back to us if they can't process the event.

**Comment by bushra** [comment]
See comment added to [Issue 1](https://github.com/nhsconnect/Events-Management/issues/1)

**Comment by james-answer** [comment]
@ahatherly I have updated the spec to make it clear for a POST to the publish API an OperationOutcome will be returned containing one of the error codes from the Spine standard error codes (You can see the changes on the netlify published version of the develop branch https://ems-develop.netlify.com/publication_publish.html#response). Do we want to try and call out the most likely causes of error responses to publishers or leave it high level as publishers should not send us invalid events.

For the subscribers recieving events I have updated the specification Event Receiver Requirements Overview page to make the existing requirements more clear that "There are currently no requirements defined for the Events Management Service to receive or act upon failures in consuming systems" (You can see the changes on the netlify published version of the develop branch, https://ems-develop.netlify.com/receiver_requirements.html#itk3-acknowledgements-and-errors). We have added a requirement that they still develope against the ITK3 Message Distribution specification just incase we want to ask for a response in the future. Do you think we should pull out some more of the key aspects of this spec and put them in the EMS spec as well as linking to the ITK3 spec.

**Comment by james-answer** [comment]
Test

**Comment by james-answer** [comment]
I am closing this for now as there is more information in the spec around error responses. If we think any more detail is required in the future we can raise more specific issues when we identify useful guidance or gaps in guidance/requirements.
