### ISSUE TITLE
Page - Help & Support - About

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#20]
The Help & Support - About page (https://developer.nhs.uk/apis/ems-beta/support_about.html) seems to be a bit confused about what it is, the following things should probably be changed or moved:

1. The FHIR section about hte STU3 fhir and DCH event alpha spec should probably be in the messaging architecture overview page as it is not really about help or support.

2. The inclusion of INTEROPen does not really add anything on this page. THe care connect profiles are talked about in the messaging architecture section. A pointer to the INTEROPen website and the information about collaboration should probably be in the overview section of the spec as it is more to do with the background of the NEMS rather than a current Help or Support detail.

3. It might be worth removing the "About" from this page as the about is covered by the overview. It might be better making this a contact us page. With an additional inforation section for contact details for service.

**Comment by bushra** [comment]
I think the content in points 1 and 2 can be removed altogether as the spec no longer covers FHIR profiles. 

Agree the About page is better presented as a Contact us page.
