### ISSUE TITLE
Example Messages

### ISSUE THREAD

**Issue by bushra** [nhsconnect/Events-Management#23]
Given the event messages have been detailed in their own implementation guides, I am proposing the https://nhsconnect.github.io/Events-Management/explore_example_messages.html page is removed. @james-answer do you have any thoughts on this?

**Comment by james-answer** [comment]
I think you are correct, the NEMS spec is around the transport rather than the event messages so I would agree that this could be removed as it is in the specific implementation guides for the different projects.

**Comment by bushra** [comment]
Great - I'll apply this change.
