### ISSUE TITLE
birthDate time extension cardinality in the patient resource

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#24]
On the Event Header Information page there is a row within the communications table which refers to the birthDate element and "patient-birthTime" extension. The row only has one cardinality so it raises the question as to if the "patient-birthTime" extension has a cardinality of 1..1 as well as the "birthDate". The birthDate element has a cardinality of 1..1 in the fhir profile but the birth time extension has a cardinality of 0..1. Is the birth time extension mandatory or is it optional as per the fhir profile?

`
Date of Birth | 1..1 | CareConnect-EMS-Patient-1 | birthDate and patient-birthTime extension
`

**Comment by bushra** [comment]
I think reference to the birthtime extension can be removed from the event header information page, as this may vary depending on the use case. Are you happy to make this change in your feature branch?

**Comment by james-answer** [comment]
Removed the birthTime extension from the guidance on the feature branch.
