### ISSUE TITLE
Use of location and organization resources

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#25]
What is the EMS definition of location and organization resources. If we do not give guidance on the population of these resources there is a wide variety of was a publisher can populate them both physically but also what they represent.

For example if you have a location it can be used to represent a specific room, a building or anything else, do we want to be specific about if you include a location linked to one of the a EMS header resources then it should he a building and include the address as strucutred data?

That leads on to the second point that if a consumer populates a location they could just include an identifier, they could include the address as strucutred data, they can include the address as a single text string. This makes it difficult for a consumer to know how to expect the data, it would be a good idea to be more specific to simplify a subscribers job when consuming information.

The same applies to an organization, what do we want publishers to use the organization resource to represent and is there any mandatory elments such as ODS Code?

**Comment by james-answer** [comment]
Proposed that Organization should be a legally recognised organization represented by an ODS Code. The resource should contain name, address and telecom information. Location should be a physical location and contain address, name and telecom information.

I will updated the specification.

**Comment by ahatherly** [comment]
Could we also consider just including a reference to the Organisation endpoint on the ODS API - e.g.: https://directory.spineservices.nhs.uk/STU3/Organization/X2601
Or, if there's some value in including the details (which there probably is for convenience), perhaps the Organization resource in the event bundle should include it's canonical URL (above) as an attribute as well?

**Comment by james-answer** [comment]
I think using the ODS API should be the first choice unless there is a strong reason to include the organization resource in the bundle. I imagine the reasons a subscriber would want to the information with the event would be:

- to display the organization to a user
- to find contact details for the organization in the event of an error

For displaying to the user we could make the `display` element within the reference mandatory if the reference is a absolute url to the ODS API so that it can easily be displayed.

If someone wants to find the organization contact details then this would be part of a work flow so it would not be unreasonable to expect them to call the ODS API to get the details. This is probably better than including a resource as the details will be up to date where as if they are from an old event they could have changed.

**Comment by james-answer** [comment]
I have updated the "EMS EVent Header Information" page on the "develop" branch, of the EMS spec, to include additional wording to say that the ODS API should be used if possible.

I think we need to make sure this is included for each of the event message implementation guides where appropriate and where the event requires reference to an organisation.

**Comment by james-answer** [comment]
Changes merged into the live version so closing.
