### ISSUE TITLE
Flesh out error scenarios

### ISSUE THREAD

**Issue by ahatherly** [nhsconnect/Events-Management#3]
There are quite a few permutations of error scenarios for both the publisher sending an event in, and errors encountered by subscribers trying to process events they receive - these will need fleshing out and describing to set expectations about behaviours of each party.

**Comment by bushra** [comment]
See comment added to [Issue 1](https://github.com/nhsconnect/Events-Management/issues/1)

**Comment by james-answer** [comment]
Additional guidance around potential errors will be added as part of uplifts to the spec for validation of the publication API. Additional guidance was added for the subscription api pointing towards the structure of the errors and error code value set. If we need more detail we can add it later but the current level of detail should allow suppliers to build and handle errors correctly so closing this issue.
