### ISSUE TITLE
Page - Introduction to Events Management Service

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#6]
The following things need to be changed or updated on the "Introduction to Events Management Service" page (https://developer.nhs.uk/apis/ems-beta/index.html).

1. This is the first page someone will land on when looking at NEMS for the first time. This page could do with a short introductory paragraph about what the NEMS is and what it is intended for.

2. Rather than the links to the event message specifications being set as example event messages they should probably be currenty supported event message specifications.

**Comment by fletch1975** [comment]
Agree - page needs to be updated.

**Comment by james-answer** [comment]
I have updated the page content with additional wording, a diagram and a short description for each of the links to the event message specification guides to say what they are. The changes have been committed to the "feature/introduction_page_updates" branch.

**Comment by james-answer** [comment]
Feedback from DF - 

•	We should be referring to the  ‘National Event Management Service’ to avoid confusion with local initiatives.
•	I think we need to provide some reference to the schedule for when events will be available through the NEMS, I don’t think it’s clear at the moment what events a supplier could subscribe to different events.

**Comment by james-answer** [comment]
I have updated all the references to EMS and Events Management Service to NEMS and National Events Management Service on the develope branch as per the feedback.

**Comment by james-answer** [comment]
This has been reviewed and after a couple of small changes has been completed.
