### ISSUE TITLE
Page - Messaging Architecture Overview

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#8]
The "Messaging Architecture Overview" page (https://developer.nhs.uk/apis/ems-beta/explore.html) could benefit from the following changes:

1. The url could do with updating to match the page title which helps find the page if someone new needs to update the page in future, "explore" -> "msg_architecture_overview"

2. The "Message Patterns and Message Structure" and "Events" sections could do with being broken up a little bit to help group concepts and explain them in a slight bit more depth. It seems a bit crushed together at the moment, jumping from one thing to another. For example the first paragraph talks about publishing and the concept of subscriptions but does not mention the passing on of events to subscribers, the events section starts by repeating that events will be sent by providers.

3. The diagram is too fucused on DCH and and could be simplified to just the NEMS function, event message, NEMS, scubscribers and messages being distrubuted. There is probably no need to have the events catalogue or specific types of providers or consumers on this diagram, they probably go into other bits of the spec.

4. The inclusion of the "Event message data item requirement notation" section with definition of Mandatory, Required and Optional does not seem to fit on this page and seems a bit out of place. It should really be with the event and resource population guidance.

**Comment by fletch1975** [comment]
I agree with all the comments here. The page needs to be updated, I'll take an action to do this.

**Comment by james-answer** [comment]
I have made some updates for the additional points and changed the diagram. Changes committed to the "feature/introduction_page_updates"

@bushra  could you review the changes, thanks

**Comment by james-answer** [comment]
Feedback from DF -

•	I like the Event Message Flow diagram but it might be worth adding MESH for completeness.
•	For the Messaging Pattern a link could be provided to our Integration Patterns pages https://developer.nhs.uk/library/architecture/integration-patterns/
•	I’d be inclined to remove the comment regarding delivery of event messages via channels other than MESH. If we introduce other channels, NHS Mail, REST API we can update the specification accordingly.

**Comment by james-answer** [comment]
I have done all the changes as per the feedback and pushed it to the "develop" branch.

In the diagram I have just put the message going through MESH and not included the MESH api or other otpions as the link to the MESH information gives the reader options around the different ways to access the mesh mailbox, API or Java App which pulls the mesh mail to a local directory without the supplier directly using the MESH API.

**Comment by james-answer** [comment]
Changes have been reviewed and after a couple of tweaks to the page, is complete and ready for release.
