### ISSUE TITLE
Page - EMS Event Header Design

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#9]
The following changes would be a good idea for the "EMS Event Header Design" page (https://developer.nhs.uk/apis/ems-beta/explore_event_header_design.html):

1. This page would be better being after the "Bundle Structure" page as it makes more sense if you read it after the page about the event message bundle structure.

2. Whole page is confusing when you first read it. It make some sense when you have learned a lot more about the specification but the information it is trying to convey is not clear. The page would benefit from a diagram and more clear wording. The links between resources are not clear.

3. The page should probably have some more specific guidance around element population within the profiled resources, for example it says that there should be one patient name but it does not say if this should be the patient name slice within the profile with the use official and does that name correspond to the name as recognised by the Spine.

4. Where profiles are mentioned they should probably be links to the profiles. The same applys to other concepts in the spec such as failsafe alerts as it is not clear they are part of this spec if you have not read those sections yet.

5. The table layout is confusing and the sub element for resources look like resources. It would be better to take it out the table and change to headers and details including cardinality and conditions. This would allow the user to more quickly see the specific resources that are part of the event header but also allow for additional detail to be added, with a table too much information looks difficult to read.

A possible change to the layout for the table could be:

Description saying that the following resources makeup the header component and will be the first resources within the Bundle event message. Include if the message bundle has a fhir profile ID or if it is just the base fhir Bundle and highlight that the bundle type is Message?

**EMS-MessageHeader-1**
- Event -> …
- Source -> …
- Responsible -> …
- Timestamp -> …
- Identifier -> …

**CareConnect-EMS-Patient-1**
- Nhs number
- DOB
- Name (use: official, desc: name as registered on PDS)

**CareConnect-Organization-1**
**CareConnect-Location-1**
**CareConnect-Encounter-1**

**Comment by bushra** [comment]
1. The page will be moved and renamed Event Header Information. 
2. I think a reference to the diagram in the Bundle Structure with Event Header Information would be sufficient. 
3. This page has been built around a single list of items as listed in the Requirements column, which is the only detail provided to date. Further detail around population of the FHIR profiles would be needed. 
4. Links to FHIR profiles have been added. The 'name' item will reference use of the 'official' slice.
5. For now, I think the table should only show the event header information requirements for communications only. The use of the EMS FHIR profiles for clinical events has not yet been explored beyond the initial bundle structure.
